## YAML Template.
---
spring:
    # NOMBRE DEL SERVICIO
    application:
        name: microservicio-keycloack
        
# ESPECIFICACIÓN DEL PUERTO.
server:
    port: 8088
    
# CONFIGURACIÓN DE EUREKA SERVER
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
            
# CONFIGURACIÓN DE KEYCLOACK SERVER
keycloak:
    base-uri: ${KEYCLOACK_SERVER:http://localhost:8091/auth/realms/}
    authorization-uri: ${keycloak.base-uri}backendchain/protocol/openid-connect/auth
    user-info-uri: ${keycloak.base-uri}backendchain/protocol/openid-connect/userinfo
    token-uri: ${keycloak.base-uri}backendchain/protocol/openid-connect/token
    logout: ${keycloak.base-uri}backendchain/protocol/openid-connect/logout
    jwk-set-uri: ${keycloak.base-uri}backendchain/protocol/openid-connect/certs
    certs-id: ${KEYCLOACK_REAL_ID:MCS_u2Iro7tpusjoFI5wGMkxss42pCfdXw4LejRSdFs}
    client-id: id-alumns-app
    client-secret: 12345
    scope: profile
    authorization-grant-type: password
    authorization-grant-type-refresh: refresh_token